# Which branch and repository are you building from?
# Where are you publishing to and which UI should you use?
content:
  sources:
  # Uncomment to build from your local git clone
  - url: .
    start_path: .
  # Uncomment to build from the remote github repository.
  #- url: https://github.com/uyuni-project/uyuni-docs.git
    # Select the branch you want to build
    # If you make changes on a branch and have the wrong branch selected you will not see your changes in your build
    branches:
    - '.'  
output:
  dir: ./build/en
runtime:
  cache_dir: ./.cache/antora
asciidoc:
  attributes:
    saltversion: 3002
    sles-version: 15
    sp-version: SP4
    sp-vert: sp3
    sp-version-l: sp3
    smrproductnumber: 4.3
    opensuse-version: 15.3
    linkattrs: True
    sectlinks: True
    sectnums: True
    sectnumlevels: 5
    icons: font
    experimental: True
    susemgr: SUSE Manager
    smr: for Retail
    uyuni: Uyuni
    slepos: SUSE Linux Enterprise Point of Service
    susemgrproxy: SUSE Manager Proxy
    sles: SUSE Linux Enterprise Server
    sle: SUSE Linux Enterprise
    es: Expanded Support
    micro: SLE Micro
    microos: MicroOS
    slsa: SLES
    suse: SUSE
    slea: SLE
    sleses: SUSE Linux Enterprise Server with Expanded Support
    sleda: SLED
    unifiedinstaller: Unified Installer
    alibabaclo: Alibaba Cloud Linux
    almalinux: AlmaLinux
    amazon: Amazon Linux
    centos: CentOS
    debian: Debian
    opensuse: openSUSE
    oracle: Oracle Linux
    redhat: Red Hat
    rhel: Red Hat Enterprise Linux
    rhela: RHEL
    rhnminrelease6: Red Hat Enterprise Linux Server 6
    rhnminrelease7: Red Hat Enterprise Linux Server 7
    rhnminrelease8: Red Hat Enterprise Linux Server 8
    rocky: Rocky Linux
    ubuntu: Ubuntu
    aarch64: aarch64
    arm64: ARM64
    ipf: Itanium
    ppc: IBM Power
    ppc64: ppc64
    ppc64le: ppc64le
    s390x: s390x
    x86: x86
    x86_64: x86-64
    ibmz: IBM Z
    zseries: IBM Z
    zsystems: IBM Z
    homepage: https://github.com/uyuni-project/uyuni-docs/
    grub: Grub
    kickstart: Kickstart
    webui: Web UI
    jeos: JeOS
    minimal: Minimal
    minimalsles: Minimal SLES
    scc: SUSE Customer Center
    ncc: Novell Customer Center
    phub: SUSE Package Hub
    ay: AutoYaST
    yast: YaST
    rootuser: root
    ruser: root
    mdash: \-
    openscap: OpenSCAP
    rmtool: Repository Management Tool
    smtool: Repository Management Tool
    vmguest: VM Guest
    vmhost: VM Host Server
    xen: Xen
    kvm: KVM
    kube: Kubernetes
    check: icon:check[role="green"]
    cross: icon:times[role="danger"]
    question: icon:question[role="gray"]
    star: icon:asterisk[role="none"]
    salt: Salt
    trad: Traditional
    imagesdir: images
    listing-caption: Listing
    mgradvtop: Advanced Topics Guide
    mgrbestpract: Best Practices Guide
    mgrgetstart: Getting Started Guide
    mgrrefguide: Reference Guide
    upgrade: Upgrade Guide
    snippet: ../../snippets/
    sourcedir: .
    source-highlighter: coderay
    toclevels: 3
    toc: left
    doctype: book
    payg: Pay-as-you-go

    productname: SUSE Manager
    productnumber: 4.3
    docversion: 4.3
    minorversion: 4.3
    suma-content: True
    uyuni-content: False
site:
  title: SUSE Manager Documentation
  start_page: suse-manager::index
  url: https://documentation.suse.com/suma/4.3/
ui:
  bundle:
    url: ./branding/default-ui/suma/susecom-ui-branding-2021.zip
    snapshot: True
  supplemental_files: ./branding/supplemental-ui/suma/susecom-branding-2021

